states_dict = {
        'AK': ('Alaska',0.23),
        'AL': ('Alabama',1.51),
        'AR': ('Arkansas',0.93),
        'AS': ('American Samoa',0.02),
        'AZ': ('Arizona',2.12),
        'CA': ('California',12.18),
        'CO': ('Colorado',1.70),
        'CT': ('Connecticut',1.13),
        'DC': ('District of Columbia',0.21),
        'DE': ('Delaware',0.29),
        'FL': ('Florida',6.31),
        'GA': ('Georgia',3.18),
        'GU': ('Guam',0.06),
        'HI': ('Hawaii',0.45),
        'IA': ('Iowa',0.97),
        'ID': ('Idaho',0.51),
        'IL': ('Illinois',4.00),
        'IN': ('Indiana',2.06),
        'KS': ('Kansas',0.91),
        'KY': ('Kentucky',1.38),
        'LA': ('Louisiana',1.45),
        'MA': ('Massachusetts',2.11),
        'MD': ('Maryland',1.87),
        'ME': ('Maine',0.41),
        'MI': ('Michigan',3.11),
        'MN': ('Minnesota',1.71),
        'MO': ('Missouri',1.89),
        'MP': ('Northern Mariana Islands',0.02),
        'MS': ('Mississippi',0.93),
        'MT': ('Montana',0.32),
        'NC': ('North Carolina',3.12),
        'ND': ('North Dakota',0.24),
        'NE': ('Nebraska',0.59),
        'NH': ('New Hampshire',0.41),
        'NJ': ('New Jersey',2.79),
        'NM': ('New Mexico', 0.65),
        'NV': ('Nevada',0.90),
        'NY': ('New York',6.16),
        'OH': ('Ohio',3.61),
        'OK': ('Oklahoma',1.22),
        'OR': ('Oregon',1.25),
        'PA': ('Pennsylvania',3.98),
        'PR': ('Puerto Rico',1.08),
        'RI': ('Rhode Island',0.33),
        'SC': ('South Carolina',1.52),
        'SD': ('South Dakota',0.27),
        'TN': ('Tennessee',2.05),
        'TX': ('Texas',8.55),
        'UT': ('Utah',0.93),
        'VA': ('Virginia',2.61),
        'VI': ('Virgin Islands',0.04),
        'VT': ('Vermont',0.19),
        'WA': ('Washington',2.23),
        'WI': ('Wisconsin',1.80),
        'WV': ('West Virginia',0.57),
        'WY': ('Wyoming',0.18)
        }
states = states_dict.values()
states_arr = [item[0] for item in states_dict.values()]
states_p = [item[1] for item in states_dict.values()]

